####################################################################################################################################
### This is an unofficial submod for Just Natsuki, a mod for Doki Doki Literature Club.                                          ###
### It is not affiliated with Team Salvato in any way.                                                                           ###
### And it is not affiliated with the Just Natsuki Team in any way either.                                                       ###
###                                                                                                                              ###
### Do not edit this file unless you know what you're doing. And as always, backup your persistent file.                         ###
### (can be found in %APPDATA%\RenPy\JustNatsuki).                                                                               ###
### This submod shouldn't mess with your save file in a way that breaks the game, but it's always better to be safe than sorry.  ###
### Especially if you want to go back to the original game later on.                                                             ###
###                                                                                                                              ###
### The goal of this submod is to add a new function called "NatBoot", what is it? Well, every time you start the game, Natsuki  ###
### sends you a message depending on her affinity! Best part? It has "Remote Notifications for Just Natsuki" support! You can    ###
### Find their mod here: https://github.com/Zombie-Bdev/Remote-Notifications-for-Just-Natsuki.                                   ###
###                                                                                                                              ###
### How does this work?                                                                                                          ###
### You see, this script runs instantly when the game boots up, in fact, it's priority is 1, which means, it'll be one of the    ###
### First mods to even boot up, but since "Remote Notifications for Just Natsuki" has a priority of -10, it loads way before     ###
### this mod, which allows this mod to use the global variables and use it to send notifications. Now, for the checks.           ###
### This mod checks for the affinity using the vanilla function called isLove, isNormal, etc etc, and using that, we can send    ###
### Start pop ups or notifications towards any device, it's very simple!                                                         ###
###                                                                                                                              ###
### Currently I **THINK** this mod only works on Windows (Unless you have RNfJN, which you can even use notifs on a smart fridge)###
####################################################################################################################################

init 1 python:
    import store.jn_activity as jn_activity
    import store.jn_utils as jn_utils
    import random

    # Custom Emotes, feel free to add more | happy_emote, angry_emote, sad_emote, tease_emote and confused_emote are all vanilla emotes. so you can call them directly.
    unimpressed_emote = random.choice([
            "(￢_￢)",
            "(¬ ¬ )",
            "(¬_¬)"
        ])
    shocked_emote = random.choice([
            ":O",
            "O.O",
            "O_O",
            "(⓿_⓿)"
        ])
    shy_emote = random.choice([
            ">.<",
            "^^;",
            "(^///^)"
        ])
    laugh_emote = random.choice([
            "XD",
            ":P",
            "(*^▽^*)"
        ])
    devious_emote = random.choice([
            ">:)",
            ">:P",
            ">:D",
            "( •̀ ω •́ )y"
        ])
    love_emote = random.choice([
            "<3",
            "^3^",
            "（づ￣3￣）づ╭❤️～",
            "(^◕.◕^)",
        ])

    def send_windows_notification(title, message):
        try:
            playername = getattr(persistent, "playername", None) or "player"

            # Translates the text so instead of sending, "Hey [player], I hate you [angry_emote]", it'll send smt like "Hey Singu, I hate you >:/".
            substituted_message = message.replace("[player]", playername)
            substituted_message = substituted_message.replace("[happy_emote]", happy_emote)
            substituted_message = substituted_message.replace("[angry_emote]", angry_emote)
            substituted_message = substituted_message.replace("[sad_emote]", sad_emote)
            substituted_message = substituted_message.replace("[tease_emote]", tease_emote)
            substituted_message = substituted_message.replace("[confused_emote]", confused_emote)

            jn_activity.notifyPopup(substituted_message)

        except Exception as e:
            jn_utils.log(
                "HAHAHAHAHAHAHAHAHAHAHAHAHA" # Don't bother lmao, this is when the mod errors or crashes, which it really shouldn't unless you edit something you either:
                    # Shouldn't have, or you messed up the indentation somewhere.
            )


    def get_boot_greeting():
        if Natsuki.isLove(higher=True): # Messages when Natsuki's Affinity is Love. In this state, she will send multiple emojis to show affection.
            greetings = [
                "Hey, [player] [love_emote] ! I was hoping you'd be back soon [happy_emote]",
                "[player]! [happy_emote] There you are, I missed you [happy_emote]",
                "You're back [love_emote]! [happy_emote] Get comfy, I've got stuff to tell you [happy_emote]",
                "Finally! [angry_emote] I was starting to miss you, you know [shy_emote]",
                "Hi [player] [devious_emote]! Ready to spend some time together? [happy_emote]",
            ]

        elif Natsuki.isAffectionate(higher=True): # Messages when Natsuki's Affinity is Affectionate or higher. In this state, she's comfortable with you and will start to use a bit of emojis.
            greetings = [
                "Oh, hey! [player], right? Good timing [happy_emote]",
                "Well, look who decided to show up. Hey, [player] [tease_emote]",
                "[player]! Hey, I was wondering when you'd be back [happy_emote]",
                "You're here! Not that I was waiting or anything [tease_emote]",
                "Hi [player]! Glad you're back [happy_emote]",
            ]

        elif Natsuki.isNormal(higher=True): # Messages when Natsuki's Affinity is Normal or higher. In this state, she is neutral but will not send emojis to keep you comfortable due to her still not knowing you much.
            greetings = [
                "Hey, [player]! What's up?",
                "Oh, [player]!",
                "You're back. Good timing, [player]",
                "Hey [player]! Long time no see, huh?",
                "Oh, hey [player]!",
            ]

        elif Natsuki.isDistressed(higher=True): # Messages when Natsuki's Affinity is distressed. In this state, she doesn't want to act "fun" with you.
            greetings = [
                "Oh. It's you, [player].",
                "[player]. Hello.",
                "You came back. Wish I could say I was happy about it.",
                "Huh. [player]. This better be good.",
                "Welcome back, I guess.",
                "You better make up for what you did."
            ]

        else:
            greetings = [ # Messages when Natsuki's Affinity is below Distressed (ex. Ruined). In this state, she's dissapointed that you even dare to come back.
                "...[player]?",
                "Oh. It's you...",
                "...Why did you come back?",
                "...",
                "I don't really have anything to say...",
                "I don't want you here."
            ]

        chosen_greeting = random.choice(greetings)

        if "jn_zpn" in globals() and hasattr(jn_zpn, "send_ntfy_notification"): # This just checks if you have "Remote Notifications for Just Natsuki" installed.
            try:
                jn_zpn.send_ntfy_notification(chosen_greeting)
            except Exception as e:
                jn_utils.log(
                    "[Relationship Submod] jn_zpn notification failed: {0}".format(
                        repr(e)
                    )
                )

        return chosen_greeting


    greeting = get_boot_greeting()
    send_windows_notification("Natsuki", greeting) # Send windows notifications.
